# microai_edu and Dockerfile must be in the same folder as docker-compose.yml
version: '3'
services:
  jupyter-tensorflow:
    image: jupyter/tensorflow-notebook
    build:
        context: .
        dockerfile: Dockerfile
    container_name: jupyter-tensorflow
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${PWD}/microai_edu:/home/jovyan/test

